version: '3'

services:

  app:
    build: .
    ports:
      - '80:80'
    links:
      - db
    volumes:
      - ./data:/var/www

  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: training
